### ISSUE TITLE
Saw Issue With LegacyRef Types  

### ISSUE THREAD

**Issue by JackHowa** [wpj/lazy-child#8]
Thanks for working on this package and setting this up. Really helpful! Noticed one small types change, wasn't sure. Let me know how I can help

Type '((instance: HTMLElement) => void) | RefObject<HTMLElement>' is not assignable to type 'LegacyRef<HTMLDivElement>'.

on build. not sure if you've seen this before

From 0.2.0 -> 0.3.1 version 

## Usage 

```jsx
      <Lazy
        offsetBottom={lazyOptions.offsetBottom}
        offsetLeft={lazyOptions.offsetLeft}
        offsetRight={lazyOptions.offsetRight}
        offsetTop={lazyOptions.offsetTop}
        renderPlaceholder={(ref): React.ReactElement => (
          <div
            ref={ref}
            style={{ height: mediumHeight, width: mediumWidth, maxWidth: '50px' }}
          />
        )}
      >
              <img
                alt={alt}
                src={'./sample-image.jpg'}
                width={largeWidth}
                height={largeHeight}
              />
</Lazy>
```

It kind of looks like the documentation for placeholder may have changed between 0.2.0 -> 0.3.0 https://github.com/wpj/lazy-child/commit/08842eec802db90386bef85169ea8f40ae3e70e9#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R20

**Comment by JackHowa** [comment]
let me know @wpj if you've seen this or have recommendations?

**Comment by wpj** [comment]
@JackHowa apologies for the delay! I didn't get a notification for this until you mentioned me for some reason. If you specify Lazy's first type parameter, e.g. `<Lazy<HTMLDivElement></Lazy>`, does that type error still occur?

**Comment by JackHowa** [comment]
no worries @wpj , thanks, will try it out when I get a sec

**Comment by JackHowa** [comment]
updated in engine theme sdk https://github.com/WPMedia/engine-theme-sdk/pull/356/files#diff-cbebe5b8251da0dffe92bd666cf4d98052868c769b4c9252e630fda88f9f8613R143
